.v q0 q1 q2 q3 q4 q5 q6

BEGIN
S q0
S q1
S q2
T q3
Z q1 q4
H q4
T* q4
Tof q0 q4
T q4
Tof q1 q4
T* q4
Tof q0 q4
T q4
Tof q5 q4
H q5
T* q5
Tof q2 q5
T q5
H q4
Tof q4 q5
T* q5
Tof q2 q5
T q5
Tof q6 q5
H q6
T* q6
Tof q3 q6
T q6
Tof q2 q4
S* q4
Tof q2 q4
S q4
Z q1 q4
H q5
T q5
Tof q5 q6
T* q6
Tof q3 q6
T q6
H q6
Tof q3 q5
T* q5
Tof q3 q5
Z q4 q5
H q5
T* q5
Tof q2 q5
T q5
Tof q4 q5
T* q5
Tof q2 q5
T q5
H q5
H q4
T* q4
Tof q0 q4
T q4
Tof q1 q4
T* q4
Tof q0 q4
T q4
H q4
Tof q0 q1
S* q1
Tof q0 q1
END
